### ISSUE TITLE
Accept extra functions into the scope when calling interpret

### ISSUE THREAD

**Issue by pasviegas** [danprince/jsxpr#3]
'interpret' function could accept one more param and mix it with 'native' so external functionsfunctions can be added.

This would be an awesome feature for someone who is delivering dynamic code to a host that has the defined functions. :)

**Comment by pasviegas** [comment]
Awesome! Thanks!! :D 

One last thing, can you publish a new release with this?

**Comment by danprince** [comment]
I can—but first, please tell me you're not doing anything serious with this?
